[package]
name = "dioxus-easyui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.3.2"
dioxus-desktop = "0.3.0"
reusable = "0.1.0"
dioxus-easyui-macros = { path = "dioxus-easyui-macros" }

[dev-dependencies]

